# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\sertan\Desktop\düzenle2\birleştirme\NetHesaplatma.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NetHesaplatma(object):
    def setupUi(self, NetHesaplatma):
        NetHesaplatma.setObjectName("NetHesaplatma")
        NetHesaplatma.resize(1211, 731)
        NetHesaplatma.setMinimumSize(QtCore.QSize(1211, 731))
        NetHesaplatma.setMaximumSize(QtCore.QSize(1211, 731))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/net.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        NetHesaplatma.setWindowIcon(icon)
        self.widget_4 = QtWidgets.QWidget(NetHesaplatma)
        self.widget_4.setGeometry(QtCore.QRect(170, 140, 1031, 571))
        self.widget_4.setAutoFillBackground(False)
        self.widget_4.setStyleSheet("border-radius: 15px;\n"
"border: 3px solid black;\n"
"background-color: rgb(255, 255, 255);")
        self.widget_4.setObjectName("widget_4")
        self.label_3 = QtWidgets.QLabel(self.widget_4)
        self.label_3.setGeometry(QtCore.QRect(360, 20, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("border-radius: 15px;\n"
"border: 0px solid black;\n"
"")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.widget_4)
        self.label_2.setGeometry(QtCore.QRect(250, 20, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border-radius: 15px;\n"
"border: 0px solid black;\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.widget_4)
        self.label_5.setGeometry(QtCore.QRect(560, 20, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("border-radius: 15px;\n"
"border: 0px solid black;\n"
"")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(self.widget_4)
        self.label_4.setGeometry(QtCore.QRect(450, 20, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("border-radius: 15px;\n"
"border: 0px solid black;\n"
"")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(self.widget_4)
        self.label.setGeometry(QtCore.QRect(150, 20, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setStyleSheet("border-radius: 15px;\n"
"border: 0px solid black;\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.btn_hesapla = QtWidgets.QPushButton(self.widget_4)
        self.btn_hesapla.setGeometry(QtCore.QRect(10, 220, 1011, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_hesapla.setFont(font)
        self.btn_hesapla.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_hesapla.setObjectName("btn_hesapla")
        self.label_7 = QtWidgets.QLabel(self.widget_4)
        self.label_7.setGeometry(QtCore.QRect(660, 20, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("border-radius: 15px;\n"
"border: 0px solid black;\n"
"")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.widget_4)
        self.label_8.setGeometry(QtCore.QRect(750, 20, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("border-radius: 15px;\n"
"border: 0px solid black;\n"
"")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.widget_4)
        self.label_9.setGeometry(QtCore.QRect(850, 20, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("border-radius: 15px;\n"
"border: 0px solid black;\n"
"")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.lne_edb_d = QtWidgets.QLineEdit(self.widget_4)
        self.lne_edb_d.setGeometry(QtCore.QRect(140, 50, 81, 31))
        self.lne_edb_d.setStyleSheet("border-radius: 15px;\n"
"border: 1px solid black;\n"
"background-color: rgb(255, 255, 255);")
        self.lne_edb_d.setObjectName("lne_edb_d")
        self.lne_edb_y = QtWidgets.QLineEdit(self.widget_4)
        self.lne_edb_y.setGeometry(QtCore.QRect(140, 100, 81, 31))
        self.lne_edb_y.setStyleSheet("border-radius: 15px;\n"
"border: 1px solid black;\n"
"background-color: rgb(255, 255, 255);")
        self.lne_edb_y.setObjectName("lne_edb_y")
        self.label_12 = QtWidgets.QLabel(self.widget_4)
        self.label_12.setGeometry(QtCore.QRect(10, 60, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("border-radius: 15px;\n"
"border: 0px solid black;\n"
"")
        self.label_12.setTextFormat(QtCore.Qt.RichText)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.widget_4)
        self.label_13.setGeometry(QtCore.QRect(10, 110, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("border-radius: 15px;\n"
"border: 0px solid black;\n"
"")
        self.label_13.setTextFormat(QtCore.Qt.RichText)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.lne_mat_d = QtWidgets.QLineEdit(self.widget_4)
        self.lne_mat_d.setGeometry(QtCore.QRect(240, 50, 81, 31))
        self.lne_mat_d.setStyleSheet("border-radius: 15px;\n"
"border: 1px solid black;\n"
"background-color: rgb(255, 255, 255);")
        self.lne_mat_d.setObjectName("lne_mat_d")
        self.lne_mat_y = QtWidgets.QLineEdit(self.widget_4)
        self.lne_mat_y.setGeometry(QtCore.QRect(240, 100, 81, 31))
        self.lne_mat_y.setStyleSheet("border-radius: 15px;\n"
"border: 1px solid black;\n"
"background-color: rgb(255, 255, 255);")
        self.lne_mat_y.setObjectName("lne_mat_y")
        self.lne_fiz_d = QtWidgets.QLineEdit(self.widget_4)
        self.lne_fiz_d.setGeometry(QtCore.QRect(340, 50, 81, 31))
        self.lne_fiz_d.setStyleSheet("border-radius: 15px;\n"
"border: 1px solid black;\n"
"background-color: rgb(255, 255, 255);")
        self.lne_fiz_d.setObjectName("lne_fiz_d")
        self.lne_fiz_y = QtWidgets.QLineEdit(self.widget_4)
        self.lne_fiz_y.setGeometry(QtCore.QRect(340, 100, 81, 31))
        self.lne_fiz_y.setStyleSheet("border-radius: 15px;\n"
"border: 1px solid black;\n"
"background-color: rgb(255, 255, 255);")
        self.lne_fiz_y.setObjectName("lne_fiz_y")
        self.lne_kim_d = QtWidgets.QLineEdit(self.widget_4)
        self.lne_kim_d.setGeometry(QtCore.QRect(440, 50, 81, 31))
        self.lne_kim_d.setStyleSheet("border-radius: 15px;\n"
"border: 1px solid black;\n"
"background-color: rgb(255, 255, 255);")
        self.lne_kim_d.setObjectName("lne_kim_d")
        self.lne_kim_y = QtWidgets.QLineEdit(self.widget_4)
        self.lne_kim_y.setGeometry(QtCore.QRect(440, 100, 81, 31))
        self.lne_kim_y.setStyleSheet("border-radius: 15px;\n"
"border: 1px solid black;\n"
"background-color: rgb(255, 255, 255);")
        self.lne_kim_y.setObjectName("lne_kim_y")
        self.lne_bio_d = QtWidgets.QLineEdit(self.widget_4)
        self.lne_bio_d.setGeometry(QtCore.QRect(540, 50, 81, 31))
        self.lne_bio_d.setStyleSheet("border-radius: 15px;\n"
"border: 1px solid black;\n"
"background-color: rgb(255, 255, 255);")
        self.lne_bio_d.setObjectName("lne_bio_d")
        self.lne_bio_y = QtWidgets.QLineEdit(self.widget_4)
        self.lne_bio_y.setGeometry(QtCore.QRect(540, 100, 81, 31))
        self.lne_bio_y.setStyleSheet("border-radius: 15px;\n"
"border: 1px solid black;\n"
"background-color: rgb(255, 255, 255);")
        self.lne_bio_y.setObjectName("lne_bio_y")
        self.lne_trh_d = QtWidgets.QLineEdit(self.widget_4)
        self.lne_trh_d.setGeometry(QtCore.QRect(640, 50, 81, 31))
        self.lne_trh_d.setStyleSheet("border-radius: 15px;\n"
"border: 1px solid black;\n"
"background-color: rgb(255, 255, 255);")
        self.lne_trh_d.setObjectName("lne_trh_d")
        self.lne_trh_y = QtWidgets.QLineEdit(self.widget_4)
        self.lne_trh_y.setGeometry(QtCore.QRect(640, 100, 81, 31))
        self.lne_trh_y.setStyleSheet("border-radius: 15px;\n"
"border: 1px solid black;\n"
"background-color: rgb(255, 255, 255);")
        self.lne_trh_y.setObjectName("lne_trh_y")
        self.lne_cog_d = QtWidgets.QLineEdit(self.widget_4)
        self.lne_cog_d.setGeometry(QtCore.QRect(740, 50, 81, 31))
        self.lne_cog_d.setStyleSheet("border-radius: 15px;\n"
"border: 1px solid black;\n"
"background-color: rgb(255, 255, 255);")
        self.lne_cog_d.setObjectName("lne_cog_d")
        self.lne_cog_y = QtWidgets.QLineEdit(self.widget_4)
        self.lne_cog_y.setGeometry(QtCore.QRect(740, 100, 81, 31))
        self.lne_cog_y.setStyleSheet("border-radius: 15px;\n"
"border: 1px solid black;\n"
"background-color: rgb(255, 255, 255);")
        self.lne_cog_y.setObjectName("lne_cog_y")
        self.lne_din_d = QtWidgets.QLineEdit(self.widget_4)
        self.lne_din_d.setGeometry(QtCore.QRect(840, 50, 81, 31))
        self.lne_din_d.setStyleSheet("border-radius: 15px;\n"
"border: 1px solid black;\n"
"background-color: rgb(255, 255, 255);")
        self.lne_din_d.setObjectName("lne_din_d")
        self.lne_din_y = QtWidgets.QLineEdit(self.widget_4)
        self.lne_din_y.setGeometry(QtCore.QRect(840, 100, 81, 31))
        self.lne_din_y.setStyleSheet("border-radius: 15px;\n"
"border: 1px solid black;\n"
"background-color: rgb(255, 255, 255);")
        self.lne_din_y.setObjectName("lne_din_y")
        self.label_14 = QtWidgets.QLabel(self.widget_4)
        self.label_14.setGeometry(QtCore.QRect(10, 150, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("border-radius: 15px;\n"
"border: 0px solid black;\n"
"")
        self.label_14.setTextFormat(QtCore.Qt.RichText)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.widget_4)
        self.label_15.setGeometry(QtCore.QRect(950, 20, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("border-radius: 15px;\n"
"border: 0px solid black;\n"
"")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.lne_fel_y = QtWidgets.QLineEdit(self.widget_4)
        self.lne_fel_y.setGeometry(QtCore.QRect(940, 100, 81, 31))
        self.lne_fel_y.setStyleSheet("border-radius: 15px;\n"
"border: 1px solid black;\n"
"background-color: rgb(255, 255, 255);")
        self.lne_fel_y.setObjectName("lne_fel_y")
        self.lne_fel_d = QtWidgets.QLineEdit(self.widget_4)
        self.lne_fel_d.setGeometry(QtCore.QRect(940, 50, 81, 31))
        self.lne_fel_d.setStyleSheet("border-radius: 15px;\n"
"border: 1px solid black;\n"
"background-color: rgb(255, 255, 255);")
        self.lne_fel_d.setObjectName("lne_fel_d")
        self.lbl_edb = QtWidgets.QLabel(self.widget_4)
        self.lbl_edb.setGeometry(QtCore.QRect(130, 150, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_edb.setFont(font)
        self.lbl_edb.setStyleSheet("border-radius: 15px;\n"
"border: 0px solid black;\n"
"")
        self.lbl_edb.setTextFormat(QtCore.Qt.RichText)
        self.lbl_edb.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_edb.setObjectName("lbl_edb")
        self.lbl_mat = QtWidgets.QLabel(self.widget_4)
        self.lbl_mat.setGeometry(QtCore.QRect(230, 150, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_mat.setFont(font)
        self.lbl_mat.setStyleSheet("border-radius: 15px;\n"
"border: 0px solid black;\n"
"")
        self.lbl_mat.setTextFormat(QtCore.Qt.RichText)
        self.lbl_mat.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_mat.setObjectName("lbl_mat")
        self.lbl_fiz = QtWidgets.QLabel(self.widget_4)
        self.lbl_fiz.setGeometry(QtCore.QRect(330, 150, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_fiz.setFont(font)
        self.lbl_fiz.setStyleSheet("border-radius: 15px;\n"
"border: 0px solid black;\n"
"")
        self.lbl_fiz.setTextFormat(QtCore.Qt.RichText)
        self.lbl_fiz.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_fiz.setObjectName("lbl_fiz")
        self.lbl_kim = QtWidgets.QLabel(self.widget_4)
        self.lbl_kim.setGeometry(QtCore.QRect(430, 150, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_kim.setFont(font)
        self.lbl_kim.setStyleSheet("border-radius: 15px;\n"
"border: 0px solid black;\n"
"")
        self.lbl_kim.setTextFormat(QtCore.Qt.RichText)
        self.lbl_kim.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_kim.setObjectName("lbl_kim")
        self.lbl_bio = QtWidgets.QLabel(self.widget_4)
        self.lbl_bio.setGeometry(QtCore.QRect(530, 150, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_bio.setFont(font)
        self.lbl_bio.setStyleSheet("border-radius: 15px;\n"
"border: 0px solid black;\n"
"")
        self.lbl_bio.setTextFormat(QtCore.Qt.RichText)
        self.lbl_bio.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_bio.setObjectName("lbl_bio")
        self.lbl_trh = QtWidgets.QLabel(self.widget_4)
        self.lbl_trh.setGeometry(QtCore.QRect(630, 150, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_trh.setFont(font)
        self.lbl_trh.setStyleSheet("border-radius: 15px;\n"
"border: 0px solid black;\n"
"")
        self.lbl_trh.setTextFormat(QtCore.Qt.RichText)
        self.lbl_trh.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_trh.setObjectName("lbl_trh")
        self.lbl_din = QtWidgets.QLabel(self.widget_4)
        self.lbl_din.setGeometry(QtCore.QRect(830, 150, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_din.setFont(font)
        self.lbl_din.setStyleSheet("border-radius: 15px;\n"
"border: 0px solid black;\n"
"")
        self.lbl_din.setTextFormat(QtCore.Qt.RichText)
        self.lbl_din.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_din.setObjectName("lbl_din")
        self.lbl_cog = QtWidgets.QLabel(self.widget_4)
        self.lbl_cog.setGeometry(QtCore.QRect(730, 150, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_cog.setFont(font)
        self.lbl_cog.setStyleSheet("border-radius: 15px;\n"
"border: 0px solid black;\n"
"")
        self.lbl_cog.setTextFormat(QtCore.Qt.RichText)
        self.lbl_cog.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_cog.setObjectName("lbl_cog")
        self.lbl_fel = QtWidgets.QLabel(self.widget_4)
        self.lbl_fel.setGeometry(QtCore.QRect(930, 150, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_fel.setFont(font)
        self.lbl_fel.setStyleSheet("border-radius: 15px;\n"
"border: 0px solid black;\n"
"")
        self.lbl_fel.setTextFormat(QtCore.Qt.RichText)
        self.lbl_fel.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_fel.setObjectName("lbl_fel")
        self.label_16 = QtWidgets.QLabel(self.widget_4)
        self.label_16.setGeometry(QtCore.QRect(300, 330, 201, 101))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("border-radius: 15px;\n"
"border: 0px solid black;\n"
"")
        self.label_16.setTextFormat(QtCore.Qt.RichText)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.lbl_top = QtWidgets.QLabel(self.widget_4)
        self.lbl_top.setGeometry(QtCore.QRect(510, 330, 201, 101))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.lbl_top.setFont(font)
        self.lbl_top.setStyleSheet("border-radius: 15px;\n"
"border: 0px solid black;\n"
"")
        self.lbl_top.setTextFormat(QtCore.Qt.RichText)
        self.lbl_top.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_top.setObjectName("lbl_top")
        self.widget_3 = QtWidgets.QWidget(NetHesaplatma)
        self.widget_3.setGeometry(QtCore.QRect(170, 10, 1031, 111))
        self.widget_3.setStyleSheet("border-radius: 15px;\n"
"border: 3px solid black;\n"
"background-color: rgb(255, 255, 255);")
        self.widget_3.setObjectName("widget_3")
        self.label_10 = QtWidgets.QLabel(self.widget_3)
        self.label_10.setGeometry(QtCore.QRect(410, 20, 211, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_10.setFont(font)
        self.label_10.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.label_10.setStyleSheet("border-radius: 0px;\n"
"border: 0px solid black;\n"
"background-color: rgb(255, 255, 255);")
        self.label_10.setTextFormat(QtCore.Qt.AutoText)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.widget = QtWidgets.QWidget(NetHesaplatma)
        self.widget.setGeometry(QtCore.QRect(10, 10, 141, 701))
        self.widget.setStyleSheet("QWidget{\n"
"    \n"
"    \n"
"    \n"
"    background-color: rgb(0, 0, 0);\n"
"    border-radius: 15px;\n"
"    border: 3px solid;\n"
"}\n"
"\n"
"")
        self.widget.setObjectName("widget")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(20, 10, 101, 101))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/icons/Sophia(1).png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.layoutWidget_3 = QtWidgets.QWidget(self.widget)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 120, 121, 561))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_home_ders = QtWidgets.QPushButton(self.layoutWidget_3)
        self.btn_home_ders.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_home_ders.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/anasayfa.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_home_ders.setIcon(icon1)
        self.btn_home_ders.setIconSize(QtCore.QSize(35, 35))
        self.btn_home_ders.setObjectName("btn_home_ders")
        self.verticalLayout.addWidget(self.btn_home_ders)
        self.btn_ogr_ders = QtWidgets.QPushButton(self.layoutWidget_3)
        self.btn_ogr_ders.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_ogr_ders.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/ogrenci.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_ogr_ders.setIcon(icon2)
        self.btn_ogr_ders.setIconSize(QtCore.QSize(35, 35))
        self.btn_ogr_ders.setObjectName("btn_ogr_ders")
        self.verticalLayout.addWidget(self.btn_ogr_ders)
        self.btn_ders_ders = QtWidgets.QPushButton(self.layoutWidget_3)
        self.btn_ders_ders.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_ders_ders.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/ders.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_ders_ders.setIcon(icon3)
        self.btn_ders_ders.setIconSize(QtCore.QSize(35, 35))
        self.btn_ders_ders.setObjectName("btn_ders_ders")
        self.verticalLayout.addWidget(self.btn_ders_ders)
        self.btn_snf_ders = QtWidgets.QPushButton(self.layoutWidget_3)
        self.btn_snf_ders.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_snf_ders.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/sınıf.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_snf_ders.setIcon(icon4)
        self.btn_snf_ders.setIconSize(QtCore.QSize(35, 35))
        self.btn_snf_ders.setObjectName("btn_snf_ders")
        self.verticalLayout.addWidget(self.btn_snf_ders)
        self.btn_net_ders = QtWidgets.QPushButton(self.layoutWidget_3)
        self.btn_net_ders.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_net_ders.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/netW.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_net_ders.setIcon(icon5)
        self.btn_net_ders.setIconSize(QtCore.QSize(35, 35))
        self.btn_net_ders.setObjectName("btn_net_ders")
        self.verticalLayout.addWidget(self.btn_net_ders)

        self.retranslateUi(NetHesaplatma)
        QtCore.QMetaObject.connectSlotsByName(NetHesaplatma)

    def retranslateUi(self, NetHesaplatma):
        _translate = QtCore.QCoreApplication.translate
        NetHesaplatma.setWindowTitle(_translate("NetHesaplatma", "Form"))
        self.label_3.setText(_translate("NetHesaplatma", "Fizik"))
        self.label_2.setText(_translate("NetHesaplatma", "Matematik"))
        self.label_5.setText(_translate("NetHesaplatma", "Biyoloji"))
        self.label_4.setText(_translate("NetHesaplatma", "Kimya"))
        self.label.setText(_translate("NetHesaplatma", "Edebiyat"))
        self.btn_hesapla.setText(_translate("NetHesaplatma", "Net Hesapla"))
        self.label_7.setText(_translate("NetHesaplatma", "Tarih"))
        self.label_8.setText(_translate("NetHesaplatma", "Coğrafya"))
        self.label_9.setText(_translate("NetHesaplatma", "Din"))
        self.label_12.setText(_translate("NetHesaplatma", "Doğru Sayısı"))
        self.label_13.setText(_translate("NetHesaplatma", "Yanlış Sayısı"))
        self.label_14.setText(_translate("NetHesaplatma", "Net"))
        self.label_15.setText(_translate("NetHesaplatma", "Felsefe"))
        self.lbl_edb.setText(_translate("NetHesaplatma", "0"))
        self.lbl_mat.setText(_translate("NetHesaplatma", "0"))
        self.lbl_fiz.setText(_translate("NetHesaplatma", "0"))
        self.lbl_kim.setText(_translate("NetHesaplatma", "0"))
        self.lbl_bio.setText(_translate("NetHesaplatma", "0"))
        self.lbl_trh.setText(_translate("NetHesaplatma", "0"))
        self.lbl_din.setText(_translate("NetHesaplatma", "0"))
        self.lbl_cog.setText(_translate("NetHesaplatma", "0"))
        self.lbl_fel.setText(_translate("NetHesaplatma", "0"))
        self.label_16.setText(_translate("NetHesaplatma", "Toplam :"))
        self.lbl_top.setText(_translate("NetHesaplatma", "0"))
        self.label_10.setText(_translate("NetHesaplatma", "Net Hesaplatma"))
import resource_rc
