# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\sertan\Desktop\düzenle2\birleştirme\OgrenciIslemleri.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OgrenciIslemleri(object):
    def setupUi(self, OgrenciIslemleri):
        OgrenciIslemleri.setObjectName("OgrenciIslemleri")
        OgrenciIslemleri.resize(1211, 731)
        OgrenciIslemleri.setMinimumSize(QtCore.QSize(1211, 731))
        OgrenciIslemleri.setMaximumSize(QtCore.QSize(1211, 731))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/ogrenci.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        OgrenciIslemleri.setWindowIcon(icon)
        self.widget = QtWidgets.QWidget(OgrenciIslemleri)
        self.widget.setGeometry(QtCore.QRect(10, 10, 141, 701))
        self.widget.setStyleSheet("QWidget{\n"
"    \n"
"    \n"
"    \n"
"    background-color: rgb(0, 0, 0);\n"
"    border-radius: 15px;\n"
"    border: 3px solid;\n"
"}\n"
"\n"
"")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(20, 10, 101, 101))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/icons/Sophia(1).png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.layoutWidget_3 = QtWidgets.QWidget(self.widget)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 120, 121, 561))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_home = QtWidgets.QPushButton(self.layoutWidget_3)
        self.btn_home.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_home.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/anasayfa.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_home.setIcon(icon1)
        self.btn_home.setIconSize(QtCore.QSize(35, 35))
        self.btn_home.setObjectName("btn_home")
        self.verticalLayout.addWidget(self.btn_home)
        self.btn_ogr = QtWidgets.QPushButton(self.layoutWidget_3)
        self.btn_ogr.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_ogr.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/ogrenciW.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_ogr.setIcon(icon2)
        self.btn_ogr.setIconSize(QtCore.QSize(35, 35))
        self.btn_ogr.setObjectName("btn_ogr")
        self.verticalLayout.addWidget(self.btn_ogr)
        self.btn_ders = QtWidgets.QPushButton(self.layoutWidget_3)
        self.btn_ders.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_ders.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/ders.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_ders.setIcon(icon3)
        self.btn_ders.setIconSize(QtCore.QSize(35, 35))
        self.btn_ders.setObjectName("btn_ders")
        self.verticalLayout.addWidget(self.btn_ders)
        self.btn_snf = QtWidgets.QPushButton(self.layoutWidget_3)
        self.btn_snf.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_snf.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/sınıf.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_snf.setIcon(icon4)
        self.btn_snf.setIconSize(QtCore.QSize(35, 35))
        self.btn_snf.setObjectName("btn_snf")
        self.verticalLayout.addWidget(self.btn_snf)
        self.btn_net = QtWidgets.QPushButton(self.layoutWidget_3)
        self.btn_net.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_net.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/net.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_net.setIcon(icon5)
        self.btn_net.setIconSize(QtCore.QSize(35, 35))
        self.btn_net.setObjectName("btn_net")
        self.verticalLayout.addWidget(self.btn_net)
        self.layoutWidget_3.raise_()
        self.label.raise_()
        self.widget_2 = QtWidgets.QWidget(OgrenciIslemleri)
        self.widget_2.setGeometry(QtCore.QRect(500, 140, 701, 571))
        self.widget_2.setStyleSheet("\n"
"background-color: rgb(100, 100, 254);\n"
"\n"
"border-radius: 15px;\n"
"border: 3px solid black;\n"
"")
        self.widget_2.setObjectName("widget_2")
        self.Widget_ogrenciIslem = QtWidgets.QTableWidget(self.widget_2)
        self.Widget_ogrenciIslem.setGeometry(QtCore.QRect(10, 10, 681, 551))
        self.Widget_ogrenciIslem.setStyleSheet("border-radius: 15px;\n"
"border: 1px solid black;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.Widget_ogrenciIslem.setRowCount(30)
        self.Widget_ogrenciIslem.setColumnCount(5)
        self.Widget_ogrenciIslem.setObjectName("Widget_ogrenciIslem")
        self.Widget_ogrenciIslem.horizontalHeader().setDefaultSectionSize(128)
        self.widget_4 = QtWidgets.QWidget(OgrenciIslemleri)
        self.widget_4.setGeometry(QtCore.QRect(170, 140, 311, 571))
        self.widget_4.setStyleSheet("border-radius: 15px;\n"
"border: 3px solid black;\n"
"background-color: rgb(255, 255, 255);")
        self.widget_4.setObjectName("widget_4")
        self.btn_ogrenciEkle = QtWidgets.QPushButton(self.widget_4)
        self.btn_ogrenciEkle.setGeometry(QtCore.QRect(20, 340, 271, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_ogrenciEkle.setFont(font)
        self.btn_ogrenciEkle.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_ogrenciEkle.setObjectName("btn_ogrenciEkle")
        self.btn_ogrenciSil = QtWidgets.QPushButton(self.widget_4)
        self.btn_ogrenciSil.setEnabled(True)
        self.btn_ogrenciSil.setGeometry(QtCore.QRect(20, 400, 271, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_ogrenciSil.setFont(font)
        self.btn_ogrenciSil.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_ogrenciSil.setObjectName("btn_ogrenciSil")
        self.btn_ogrenciGunc = QtWidgets.QPushButton(self.widget_4)
        self.btn_ogrenciGunc.setGeometry(QtCore.QRect(20, 460, 271, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_ogrenciGunc.setFont(font)
        self.btn_ogrenciGunc.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_ogrenciGunc.setObjectName("btn_ogrenciGunc")
        self.label_10 = QtWidgets.QLabel(self.widget_4)
        self.label_10.setGeometry(QtCore.QRect(20, 190, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("border-radius: 15px;\n"
"border: 0px solid black;\n"
"")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_9 = QtWidgets.QLabel(self.widget_4)
        self.label_9.setGeometry(QtCore.QRect(20, 140, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("border-radius: 15px;\n"
"border: 0px solid black;\n"
"")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.lne_ogrenciAd = QtWidgets.QLineEdit(self.widget_4)
        self.lne_ogrenciAd.setGeometry(QtCore.QRect(140, 30, 161, 31))
        self.lne_ogrenciAd.setStyleSheet("border-radius: 15px;\n"
"border: 1px solid black;\n"
"")
        self.lne_ogrenciAd.setObjectName("lne_ogrenciAd")
        self.lne_veliTel = QtWidgets.QLineEdit(self.widget_4)
        self.lne_veliTel.setGeometry(QtCore.QRect(140, 180, 161, 31))
        self.lne_veliTel.setStyleSheet("border-radius: 15px;\n"
"border: 1px solid black;\n"
"")
        self.lne_veliTel.setObjectName("lne_veliTel")
        self.label_11 = QtWidgets.QLabel(self.widget_4)
        self.label_11.setGeometry(QtCore.QRect(20, 240, 71, 16))
        self.label_11.setStyleSheet("border-radius: 15px;\n"
"border: 0px solid black;\n"
"")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.lne_ogrenciTel = QtWidgets.QLineEdit(self.widget_4)
        self.lne_ogrenciTel.setGeometry(QtCore.QRect(140, 130, 161, 31))
        self.lne_ogrenciTel.setStyleSheet("border-radius: 15px;\n"
"border: 1px solid black;\n"
"")
        self.lne_ogrenciTel.setObjectName("lne_ogrenciTel")
        self.label_8 = QtWidgets.QLabel(self.widget_4)
        self.label_8.setGeometry(QtCore.QRect(10, 40, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("border-radius: 15px;\n"
"border: 0px solid black;\n"
"")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.lne_ogrenciSoyad = QtWidgets.QLineEdit(self.widget_4)
        self.lne_ogrenciSoyad.setGeometry(QtCore.QRect(140, 80, 161, 31))
        self.lne_ogrenciSoyad.setStyleSheet("border-radius: 15px;\n"
"border: 1px solid black;\n"
"")
        self.lne_ogrenciSoyad.setObjectName("lne_ogrenciSoyad")
        self.label_12 = QtWidgets.QLabel(self.widget_4)
        self.label_12.setGeometry(QtCore.QRect(20, 90, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("border-radius: 15px;\n"
"border: 0px solid black;\n"
"")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.comboBox_ogrenciSinif = QtWidgets.QComboBox(self.widget_4)
        self.comboBox_ogrenciSinif.setGeometry(QtCore.QRect(140, 230, 161, 31))
        self.comboBox_ogrenciSinif.setStyleSheet("border-radius: 0px;\n"
"border: 1px solid black;\n"
"")
        self.comboBox_ogrenciSinif.setObjectName("comboBox_ogrenciSinif")
        self.widget_3 = QtWidgets.QWidget(OgrenciIslemleri)
        self.widget_3.setGeometry(QtCore.QRect(170, 10, 1031, 111))
        self.widget_3.setStyleSheet("border-radius: 15px;\n"
"border: 3px solid black;\n"
"background-color: rgb(255, 255, 255);")
        self.widget_3.setObjectName("widget_3")
        self.label_13 = QtWidgets.QLabel(self.widget_3)
        self.label_13.setGeometry(QtCore.QRect(20, 20, 231, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_13.setFont(font)
        self.label_13.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.label_13.setStyleSheet("border-radius: 0px;\n"
"border: 0px solid black;\n"
"background-color: rgb(255, 255, 255);")
        self.label_13.setTextFormat(QtCore.Qt.AutoText)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.lne_ogrenciAra = QtWidgets.QLineEdit(self.widget_3)
        self.lne_ogrenciAra.setGeometry(QtCore.QRect(560, 40, 288, 30))
        self.lne_ogrenciAra.setMinimumSize(QtCore.QSize(288, 0))
        self.lne_ogrenciAra.setMaximumSize(QtCore.QSize(288, 30))
        self.lne_ogrenciAra.setStyleSheet("border-radius: 15px;\n"
"border: 1px solid black;\n"
"")
        self.lne_ogrenciAra.setObjectName("lne_ogrenciAra")
        self.label_7 = QtWidgets.QLabel(self.widget_3)
        self.label_7.setGeometry(QtCore.QRect(320, 40, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("border-radius: 15px;\n"
"border: 0px solid black;\n"
"")
        self.label_7.setObjectName("label_7")
        self.btn_ogrenciAra = QtWidgets.QPushButton(self.widget_3)
        self.btn_ogrenciAra.setGeometry(QtCore.QRect(869, 40, 141, 30))
        self.btn_ogrenciAra.setMinimumSize(QtCore.QSize(100, 0))
        self.btn_ogrenciAra.setMaximumSize(QtCore.QSize(9999, 30))
        self.btn_ogrenciAra.setStyleSheet("border-radius: 15px;\n"
"border: 1px solid black;\n"
"")
        self.btn_ogrenciAra.setIconSize(QtCore.QSize(20, 20))
        self.btn_ogrenciAra.setObjectName("btn_ogrenciAra")

        self.retranslateUi(OgrenciIslemleri)
        QtCore.QMetaObject.connectSlotsByName(OgrenciIslemleri)

    def retranslateUi(self, OgrenciIslemleri):
        _translate = QtCore.QCoreApplication.translate
        OgrenciIslemleri.setWindowTitle(_translate("OgrenciIslemleri", "Öğrenci İşlemleri"))
        self.btn_ogrenciEkle.setText(_translate("OgrenciIslemleri", "Ekle"))
        self.btn_ogrenciSil.setText(_translate("OgrenciIslemleri", "Sil"))
        self.btn_ogrenciGunc.setText(_translate("OgrenciIslemleri", "Güncelle"))
        self.label_10.setText(_translate("OgrenciIslemleri", "Veli Telefon"))
        self.label_9.setText(_translate("OgrenciIslemleri", "Öğrenci Telefon"))
        self.label_11.setText(_translate("OgrenciIslemleri", "Öğrenci Sınıfı"))
        self.label_8.setText(_translate("OgrenciIslemleri", "Öğrenci Adı"))
        self.label_12.setText(_translate("OgrenciIslemleri", "Öğrenci Soyadı"))
        self.label_13.setText(_translate("OgrenciIslemleri", "Öğrenci İşlemleri"))
        self.label_7.setText(_translate("OgrenciIslemleri", "Aramak İstediğiniz Metni Girin"))
        self.btn_ogrenciAra.setText(_translate("OgrenciIslemleri", "Ara"))
import resource_rc
