# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\sertan\Desktop\sss\birleştirme\SinifIslem.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SinifIslemleri(object):
    def setupUi(self, SinifIslemleri):
        SinifIslemleri.setObjectName("SinifIslemleri")
        SinifIslemleri.resize(1211, 731)
        SinifIslemleri.setMinimumSize(QtCore.QSize(1211, 731))
        SinifIslemleri.setMaximumSize(QtCore.QSize(1211, 731))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/sınıf.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SinifIslemleri.setWindowIcon(icon)
        self.widget_4 = QtWidgets.QWidget(SinifIslemleri)
        self.widget_4.setGeometry(QtCore.QRect(170, 140, 311, 571))
        self.widget_4.setStyleSheet("\n"
"\n"
"    border-radius: 15px;\n"
"    border: 3px solid black;\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"")
        self.widget_4.setObjectName("widget_4")
        self.lne_snfAd = QtWidgets.QLineEdit(self.widget_4)
        self.lne_snfAd.setGeometry(QtCore.QRect(130, 60, 161, 31))
        self.lne_snfAd.setStyleSheet("border-radius: 15px;\n"
"border: 1px solid black;\n"
"background-color: rgb(255, 255, 255);")
        self.lne_snfAd.setObjectName("lne_snfAd")
        self.label_8 = QtWidgets.QLabel(self.widget_4)
        self.label_8.setGeometry(QtCore.QRect(20, 70, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("border-radius: 0px;\n"
"border: 0px solid black;\n"
"")
        self.label_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_8.setTextFormat(QtCore.Qt.AutoText)
        self.label_8.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_8.setObjectName("label_8")
        self.btn_snfSil = QtWidgets.QPushButton(self.widget_4)
        self.btn_snfSil.setEnabled(True)
        self.btn_snfSil.setGeometry(QtCore.QRect(20, 310, 271, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_snfSil.setFont(font)
        self.btn_snfSil.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_snfSil.setObjectName("btn_snfSil")
        self.btn_snfEkle = QtWidgets.QPushButton(self.widget_4)
        self.btn_snfEkle.setGeometry(QtCore.QRect(20, 220, 271, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_snfEkle.setFont(font)
        self.btn_snfEkle.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_snfEkle.setObjectName("btn_snfEkle")
        self.btn_snfgunc = QtWidgets.QPushButton(self.widget_4)
        self.btn_snfgunc.setEnabled(True)
        self.btn_snfgunc.setGeometry(QtCore.QRect(20, 400, 271, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_snfgunc.setFont(font)
        self.btn_snfgunc.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_snfgunc.setObjectName("btn_snfgunc")
        self.widget = QtWidgets.QWidget(SinifIslemleri)
        self.widget.setGeometry(QtCore.QRect(10, 10, 141, 701))
        self.widget.setStyleSheet("QWidget{\n"
"    \n"
"    \n"
"    \n"
"    background-color: rgb(0, 0, 0);\n"
"    border-radius: 15px;\n"
"    border: 3px solid;\n"
"}\n"
"\n"
"")
        self.widget.setObjectName("widget")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(20, 10, 101, 101))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/icons/Sophia(1).png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.layoutWidget_3 = QtWidgets.QWidget(self.widget)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 120, 121, 561))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_home = QtWidgets.QPushButton(self.layoutWidget_3)
        self.btn_home.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_home.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/anasayfa.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_home.setIcon(icon1)
        self.btn_home.setIconSize(QtCore.QSize(35, 35))
        self.btn_home.setObjectName("btn_home")
        self.verticalLayout.addWidget(self.btn_home)
        self.btn_ogr = QtWidgets.QPushButton(self.layoutWidget_3)
        self.btn_ogr.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_ogr.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/ogrenci.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_ogr.setIcon(icon2)
        self.btn_ogr.setIconSize(QtCore.QSize(35, 35))
        self.btn_ogr.setObjectName("btn_ogr")
        self.verticalLayout.addWidget(self.btn_ogr)
        self.btn_ders = QtWidgets.QPushButton(self.layoutWidget_3)
        self.btn_ders.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_ders.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/ders.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_ders.setIcon(icon3)
        self.btn_ders.setIconSize(QtCore.QSize(35, 35))
        self.btn_ders.setObjectName("btn_ders")
        self.verticalLayout.addWidget(self.btn_ders)
        self.btn_snf = QtWidgets.QPushButton(self.layoutWidget_3)
        self.btn_snf.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_snf.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/sınıfW.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_snf.setIcon(icon4)
        self.btn_snf.setIconSize(QtCore.QSize(35, 35))
        self.btn_snf.setObjectName("btn_snf")
        self.verticalLayout.addWidget(self.btn_snf)
        self.btn_net = QtWidgets.QPushButton(self.layoutWidget_3)
        self.btn_net.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_net.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/net.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_net.setIcon(icon5)
        self.btn_net.setIconSize(QtCore.QSize(35, 35))
        self.btn_net.setObjectName("btn_net")
        self.verticalLayout.addWidget(self.btn_net)
        self.widget_2 = QtWidgets.QWidget(SinifIslemleri)
        self.widget_2.setGeometry(QtCore.QRect(500, 140, 701, 571))
        self.widget_2.setStyleSheet("\n"
"background-color: rgb(100, 100, 254);\n"
"\n"
"border-radius: 15px;\n"
"border: 3px solid black;\n"
"")
        self.widget_2.setObjectName("widget_2")
        self.Widget_snf = QtWidgets.QTableWidget(self.widget_2)
        self.Widget_snf.setGeometry(QtCore.QRect(10, 10, 681, 551))
        self.Widget_snf.setStyleSheet("border-radius: 0px;\n"
"border: 1px solid black;\n"
"background-color: rgb(255, 255, 255);")
        self.Widget_snf.setRowCount(30)
        self.Widget_snf.setColumnCount(1)
        self.Widget_snf.setObjectName("Widget_snf")
        self.Widget_snf.horizontalHeader().setDefaultSectionSize(640)
        self.widget_3 = QtWidgets.QWidget(SinifIslemleri)
        self.widget_3.setGeometry(QtCore.QRect(170, 10, 1031, 111))
        self.widget_3.setStyleSheet("border-radius: 15px;\n"
"border: 3px solid black;\n"
"background-color: rgb(255, 255, 255);")
        self.widget_3.setObjectName("widget_3")
        self.label_10 = QtWidgets.QLabel(self.widget_3)
        self.label_10.setGeometry(QtCore.QRect(10, 20, 231, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_10.setFont(font)
        self.label_10.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.label_10.setStyleSheet("border-radius: 0px;\n"
"border: 0px solid black;\n"
"background-color: rgb(255, 255, 255);")
        self.label_10.setTextFormat(QtCore.Qt.AutoText)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.btn_ogrenciAra = QtWidgets.QPushButton(self.widget_3)
        self.btn_ogrenciAra.setGeometry(QtCore.QRect(900, 40, 121, 30))
        self.btn_ogrenciAra.setMinimumSize(QtCore.QSize(100, 0))
        self.btn_ogrenciAra.setMaximumSize(QtCore.QSize(9999, 30))
        self.btn_ogrenciAra.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_ogrenciAra.setStyleSheet("border-radius: 15px;\n"
"border: 1px solid black;\n"
"")
        self.btn_ogrenciAra.setIconSize(QtCore.QSize(20, 20))
        self.btn_ogrenciAra.setObjectName("btn_ogrenciAra")
        self.label_9 = QtWidgets.QLabel(self.widget_3)
        self.label_9.setGeometry(QtCore.QRect(310, 40, 261, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.label_9.setStyleSheet("border-radius: 0px;\n"
"border: 0px solid black;\n"
"background-color: rgb(255, 255, 255);")
        self.label_9.setTextFormat(QtCore.Qt.AutoText)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.cmb_snfara = QtWidgets.QComboBox(self.widget_3)
        self.cmb_snfara.setGeometry(QtCore.QRect(600, 40, 288, 30))
        self.cmb_snfara.setStyleSheet("border-radius: 0px;\n"
"border: 1px solid black;\n"
"background-color: rgb(255, 255, 255);")
        self.cmb_snfara.setObjectName("cmb_snfara")
        self.cmb_snfara.addItem("")

        self.retranslateUi(SinifIslemleri)
        QtCore.QMetaObject.connectSlotsByName(SinifIslemleri)

    def retranslateUi(self, SinifIslemleri):
        _translate = QtCore.QCoreApplication.translate
        SinifIslemleri.setWindowTitle(_translate("SinifIslemleri", "Sınıf İşlemleri"))
        self.label_8.setText(_translate("SinifIslemleri", "Sınıf Adı"))
        self.btn_snfSil.setText(_translate("SinifIslemleri", "Sil"))
        self.btn_snfEkle.setText(_translate("SinifIslemleri", "Ekle"))
        self.btn_snfgunc.setText(_translate("SinifIslemleri", "Güncelle"))
        self.label_10.setText(_translate("SinifIslemleri", "Sınıf İşlemleri"))
        self.btn_ogrenciAra.setText(_translate("SinifIslemleri", "Filtrele"))
        self.label_9.setText(_translate("SinifIslemleri", "Aramak İstediğiniz Sınıfı Seçin"))
        self.cmb_snfara.setItemText(0, _translate("SinifIslemleri", "tümü"))
import resource_rc
